# Generated by Django 5.2 on 2025-09-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feetype",
            name="charge",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Your admin/service charge",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="feetype",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=1000, editable=False, max_digits=10
            ),
            preserve_default=False,
        ),
    ]
