# Generated by Django 5.2 on 2025-09-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_feetype_charge_feetype_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecord",
            name="charge",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
