# Generated by Django 5.2 on 2025-09-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_paymentsession_paymentrecord_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentsession",
            name="paystack_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
