# Generated by Django 5.2 on 2025-09-19 20:10

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_paymentsession_paystack_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrecord",
            name="proof_of_payment",
            field=models.FileField(
                blank=True, null=True, upload_to=payments.models.user_directory_path
            ),
        ),
    ]
