# Generated by Django 5.2 on 2025-09-21 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_alter_paymentrecord_proof_of_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum total amount (inclusive) for this rule to apply",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum total amount (inclusive) for this rule to apply",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "min_fee_count",
                    models.PositiveIntegerField(
                        default=1, help_text="Minimum number of selected fees"
                    ),
                ),
                (
                    "max_fee_count",
                    models.PositiveIntegerField(
                        default=10, help_text="Maximum number of selected fees"
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("flat", "Flat Fee"),
                            ("percent", "Percentage Discount"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Flat fee (₦) or percent (e.g., enter 20 for 20%) depending on rule type",
                        max_digits=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the rule"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["min_total_amount", "min_fee_count"],
            },
        ),
    ]
