# Generated by Django 5.2 on 2025-09-21 14:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=accounts.models.user_directory_path
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="school_portal_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
