# Generated by Django 5.2 on 2025-09-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricingoption",
            name="conditions",
        ),
        migrations.RemoveField(
            model_name="pricingoption",
            name="extra_notes",
        ),
        migrations.AddField(
            model_name="pricingoption",
            name="cta_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="pricingoption",
            name="cta_text",
            field=models.CharField(default="hi", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricingoption",
            name="features",
            field=models.TextField(
                default=1, help_text="Use newline-separated features"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricingoption",
            name="headline",
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
